version: "3.7"
services:
  iperf:
    build:
      context: .
      dockerfile: Dockerfile-iperf
    command: ["iperf", "-s", "-p 5001"]
    ports:
      - "5001:5001"

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    environment:
      PROFILING_SUPPORT_SERVER: "${SERVER}"
      LINKERD2_PROXY_LOG: "${LINKERD2_PROXY_LOG}"
      PRECMD:
    entrypoint: ["${PRECMD}", "/usr/lib/linkerd/linkerd2-proxy"]
    depends_on:
      - iperf
      - fortio
    ports:
      - "4191:4191"
      - "4140:4140"
      - "4143:4143"

  fortio:
    build:
      context: .
      dockerfile: Dockerfile-fortio
    command: ["fortio", "server"]
    ports:
      - "8080:8080"
      - "8079:8079"
    volumes:
      - type: bind
        source: "."
        target: "/out"
