version: "3.7"
services:
  iperf:
    build:
      context: .
      dockerfile: Dockerfile-iperf
    command: ["iperf", "-s", "-p 5001"]
    ports:
      - "5001:5001"

  proxy:
    build:
      context: ..
      dockerfile: profiling/Dockerfile-proxy
    environment:
      PROFILING_SUPPORT_SERVER: "${SERVER}"
      LINKERD2_PROXY_LOG: "${LINKERD2_PROXY_LOG}"
      PRECMD:
    entrypoint: bash -c "set -x ; $PRECMD /usr/lib/linkerd/linkerd2-proxy"
    command: bash -c "set -x ; $PRECMD /usr/lib/linkerd/linkerd2-proxy"
    depends_on:
      - iperf
      - fortio
    ports:
      - "4191:4191"
      - "4140:4140"
      - "4143:4143"
    cap_add:
      # Ideally there would be a seccomp profile that adds _just_ the
      # `perf_event_open` syscall so we don't have to give the proxy container
      # other privelieges. Unfortunately, compose doesn't let you pass seccomp
      # args AFAICT.
      - CAP_SYS_ADMIN

  fortio:
    build:
      context: .
      dockerfile: Dockerfile-fortio
    command: ["fortio", "server"]
    ports:
      - "8080:8080"
      - "8079:8079"
    volumes:
      - type: bind
        source: "."
        target: "/out"
