version: "3.7"
services:

  proxy:
    build:
      context: ..
      dockerfile: profiling/Dockerfile-proxy
    environment:
      LINKERD2_PROXY_LOG: "${LINKERD2_PROXY_LOG}"
    depends_on:
      - fortio-server
    security_opt:
      - seccomp:./seccomp-perf.json
    volumes:
      - type: bind
        source: "${OUT_DIR}"
        target: "/out"
    network_mode: container:fortio_server_1

  fortio-server:
    build:
      context: .
      dockerfile: Dockerfile-util

    entrypoint: ["fortio", "server"]

    volumes:
      - type: bind
        source: "${OUT_DIR}"
        target: "/out"

  fortio-server:
    build:
      context: .
      dockerfile: Dockerfile-util

    entrypoint: ["fortio", "server"]

    volumes:
      - type: bind
        source: "${OUT_DIR}"
        target: "/out"
