version: "3"
services:
  iperf:
    image: phlak/iperf
    ports:
      - "5001:5001"
  proxy:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - PROFILE=true
    environment:
      PROFILING_SUPPORT_SERVER: "iperf:5001"
    depends_on:
      - iperf
    ports:
      - "4191:4191"
      - "4140:4140"
      - "4143:4143"
  fortio:
    build:
      context: .
      dockerfile: Dockerfile-fortio
    command:
      [
        # before running fortio, wait for the proxy to be ready.
        "/linkerd-await",
        "--uri http://proxy:4191/ready",
    #     "--",
    #     "/fortio",
    #     "load",
    #     "$COMMAND",
    #     "-keepalive=false",
    #     "-H 'Host: transparency.test.svc.cluster.local'",
    #     "-payload-size=$PAYLOAD_SIZE",
    #     "-c=$CONNECTIONS",
    #     "-t=$DURATION",
    #     "-qps=$QPS",
    #     "-labels=$RUN_NAME",
    #     "-json=out/$NAME-$QPS-rps.$ID.json",
    #     "proxy:$PROXY_PORT",
      ]
    # environment:
    #   - PAYLOAD_SIZE
    #   - QPS
    #   - RUN_NAME
    #   - CONNECTIONS
    #   - DURATION
    #   - COMMAND
    #   - PROXY_PORT
    depends_on:
      - proxy
