[package]
name = "linkerd2-stack"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false
description = """
Utilities for composing Tower services.
"""

[dependencies]
futures = "0.3"
linkerd2-error = { path = "../error" }
tower = "0.3"
pin-project = "0.4"
tokio = {version = "0.2", features = ["macros"]}