[package]
name = "linkerd2-stack-tracing"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false

[dependencies]
futures = "0.3"
linkerd2-error = { path = "../../error" }
linkerd2-stack = { path = ".." }
tower = "0.3"
tracing = "0.1"
tracing-futures = { version = "0.1", features = ["std-future"] }
pin-project = "0.4"