[package]
name = "linkerd2-io"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false
description = """
General I/O primitives.
"""

[dependencies]
bytes = "0.5"
tokio = { version = "0.2", features = ["io-util", "net"] }
tokio-rustls = "0.10"
