[package]
name = "linkerd2-proxy-discover"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false
description = """
Utilities to implement a Discover with the core Resolve type
"""


[dependencies]
futures = "0.3"
linkerd2-error = { path = "../../error" }
linkerd2-proxy-core = { path = "../core" }
indexmap = "1.0"
tokio = { version = "0.2", features = ["sync", "time", "stream"] }
tracing = "0.1"
tracing-futures = "0.1"
pin-project = "0.4"

[dependencies.tower]
version = "0.3"
# disable tower's tracing `log` integration for performance reasons, since we
# will consume tower's traces as traces.
default-features = false
features = ["discover"]

[dev-dependencies]
tower-util = "0.1"
