[package]
name = "linkerd2-proxy-core"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false
description = """
Core interfaces needed to implement proxy components
"""

[dependencies]
futures = {package = "futures", version = "0.3" }
linkerd2-error = { path = "../../error" }
tokio = "0.2"
tower = "0.3"
tracing-futures = "0.2"
pin-project = "0.4"