name: Security audit

on:
  schedule:
    # 5AM Pacific
    - cron: '0 13 * * *'
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@e0938ba # v1
      - uses: actions/checkout@722adc6 # v2
      - name: audit
        run: cargo audit
